### ISSUE TITLE
Config initialization

### ISSUE THREAD

**Issue by SlamaFR** [SlamaFR/UGE-Bot#95]
So, I was setting up a fresh Docker installation, and ran into an annoying problem. If the data and/or config directories doesn't exist, the bot crashes into a StackOverflowError:
```java
Exception in thread "main" java.lang.StackOverflowError
    at java.base/java.io.UnixFileSystem.normalize(UnixFileSystem.java:76)
    at java.base/java.io.UnixFileSystem.normalize(UnixFileSystem.java:100)
    at java.base/java.io.File.<init>(File.java:280)
    at io.slama.core.BotConfiguration$shusherConfig$2.invoke(config.kt:250)
    at io.slama.core.BotConfiguration$shusherConfig$2.invoke(config.kt:249)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at io.slama.core.BotConfiguration.getShusherConfig(config.kt:249)
    at io.slama.core.BotConfiguration.access$getShusherConfig(config.kt:31)
    at io.slama.core.BotConfiguration$Companion.getShusher(config.kt:41)
    at io.slama.core.BotConfiguration$Companion.resetConfig(config.kt:72)
    at io.slama.core.BotConfiguration$shusherConfig$2.invoke(config.kt:252)
    at io.slama.core.BotConfiguration$shusherConfig$2.invoke(config.kt:249)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
    at io.slama.core.BotConfiguration.getShusherConfig(config.kt:249)
    at io.slama.core.BotConfiguration.access$getShusherConfig(config.kt:31)
    at io.slama.core.BotConfiguration$Companion.getShusher(config.kt:41)
    at io.slama.core.BotConfiguration$Companion.resetConfig(config.kt:72)
    at io.slama.core.BotConfiguration$shusherConfig$2.invoke(config.kt:252)
    at io.slama.core.BotConfiguration$shusherConfig$2.invoke(config.kt:249)
    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
...
```
Should be easily fixable.

**Comment by ZwenDo** [comment]
👍
